platform :ios, '8.0'

target 'NoChat-Example' do
    
    pod 'NoChat', :path => '../../'
    pod 'NOCProtoKit', :path => '../'
    pod 'YYText'
    pod 'YYImage', '~> 1.0.4'
    pod 'HPGrowingTextView'

end
